server:
  type: default
  minThreads:  12
  maxThreads: 48
  maxQueuedRequests: 2048
  idleThreadTimeout: 10 seconds
  # Never change the following param!
  rootPath: /api

mongoUri: "mongodb://${MONGO_HOST:-localhost}/${MONGO-DB:-zucchini}?connectTimeoutMS=5000&socketTimeoutMS=90000&w=majority&journal=true&wtimeoutMS=60000"

eggplantUri: ""

numberLatest: 100

logging:
  level: INFO

correctionAction:
  - actionCode: EXACT_REPLAY
    actionLabel: Rejeu à l'identique
    type: PASSED
  - actionCode: HAND_REPLAY
    actionLabel: Rejeu manuel
    type: PASSED
  - actionCode: DATASET
    actionLabel: Absence de jeux de données
    type: NOT_RUN
  - actionCode: FUNCTIONAL_ANOMALY
    actionLabel: Anomalie fonctionnelle
    type: FAILED

encounteredProblem:
  - longLabel: OTHER
    shortLabel: UNKNOWN
  - longLabel: AAA
    shortLabel: BBB
